baseURL = "https://codecakes.github.io/membrane/"
languageCode = "en-us"
title = "Membrane"
theme = "strange-case"
canonifyurls = true
hideHUGOSupport = true
paginate = 2
copyright = ""
licenselink = "https://github.com/codecakes/membrane/blob/develop/LICENSE"
enableRobotsTXT = true


[[menu.icons]]
	name = "GitHub"
  post = "<img src=\"/github-logo.png\">"
	url = "https://github.com/codecakes/membrane"

[[menu.main]]
	name = "GitHub"
	post = "<img src=\"/github-logo.png\">"
	url = "https://github.com/codecakes/membrane"

[params]
    GitHubUser = "codecakes"
    SidebarRecentLimit = 5
    colorScheme="scheme-slate"
    DateFormat = "2 Apr 2021"
    description = "Skunkwork for Distributed Cellular AI systems."
    sidebarFreeText = "Could be something, could be nothing."

[permalinks]
  posts = "/:year/:month/:title/"